[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Honeypot"
descriptipn = "Honeypot"
dynamic = ["version"]
requires-python = ">=3.14"
dependencies = [
    "requests",
    "docker",
    "loguru>=0.7.3",
    "basedpyright>=1.38.1",
    "ruff>=0.15.2",
]

[project.optional-dependencies]
test = [
    "pytest-asyncio"
]


[tool.hatch.version]
path = "VERSION"
pattern = "(?P<version>\\S+)"
